version: "3.7"

services:
  server:
    image: gitea/gitea:1
    restart: always
    environment:
    - VIRTUAL_HOST=git.yourdomain.com
    - VIRTUAL_PORT=3000
    - LETSENCRYPT_HOST=git.yourdomain.com
    - LETSENCRYPT_EMAIL=email@domain.com
    networks:
    - gitea
    - internal
    volumes:
    - data:/data
    - /root/git/gitea:/data/gitea/conf:rw
    expose:
    - "3000"
    - "22"
    depends_on:
    - db
  db:
    image: postgres:11-alpine
    restart: always
    environment:
    - POSTGRES_USER=testuser
    - POSTGRES_PASSWORD=testpassword
    - POSTGRES_DB=gitea
    networks:
      gitea:
        aliases:
        - db
    expose:
    - "5432"
    volumes:
    - db:/var/lib/postgresql/data
networks:
  gitea:
  internal:
    external: true
    name: internal
volumes:
  data:
  db:
