version: "3.7"

services:
  server:
    image: gitea/gitea:1
    environment:
    - APP_NAME=Gitea
    - RUN_MODE=prod
    - SSH_DOMAIN=git.dabbertorres.dev
    - SSH_PORT=22
    - HTTP_PORT=3000
    - ROOT_URL=git.dabbertorres.dev
    - DB_TYPE=postgres
    - DB_HOST=db.gitea:5432
    - DB_NAME=gitea
    - DB_USER=gitea
    - DB_PASSWD=gitea
    - VIRTUAL_HOST=git.dabbertorres.dev
    - VIRTUAL_PORT=3000
    - LETSENCRYPT_HOST=git.dabbertorres.dev
    - LETSENCRYPT_EMAIL=adiverso93@gmail.com
    networks:
    - gitea
    - internal
    volumes:
    - data:/data
    ports:
    - "3000"
    - "22"
    depends_on:
    - db
  db:
    image: postgres:11-alpine
    environment:
    - POSTGRES_USER=gitea
    - POSTGRES_PASSWORD=gitea
    - POSTGRES_DB=gitea
    networks:
      gitea:
        aliases:
        - db
    volumes:
    - db:/var/lib/postgresql/data
networks:
  gitea:
  internal:
    external: true
    name: internal
volumes:
  data:
  db:
