version: "3.7"

services:
  server:
    image: gitea/gitea:1
    environment:
    - VIRTUAL_HOST=git.dabbertorres.dev
    - VIRTUAL_PORT=3000
    - LETSENCRYPT_HOST=git.dabbertorres.dev
    - LETSENCRYPT_EMAIL=<email address>
    networks:
    - gitea
    - internal
    volumes:
    - data:/data
    - /root/git/gitea:/data/gitea/conf:rw
    ports:
    - "3000"
    - "22"
    depends_on:
    - db
  db:
    image: postgres:11-alpine
    environment:
    - POSTGRES_USER=
    - POSTGRES_PASSWORD=
    - POSTGRES_DB=
    networks:
      gitea:
        aliases:
        - db
    volumes:
    - db:/var/lib/postgresql/data
networks:
  gitea:
  internal:
    external: true
    name: internal
volumes:
  data:
  db:
