version: "3.7"

services:
  registry:
    restart: always
    image: registry:2
    environment:
    - VIRTUAL_HOST=docker.yourdomain.com
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=docker.yourdomain.com
    - LETSENCRYPT_EMAIL=email3@domain.com
    expose:
    - "80"
    - "443"
    networks:
    - internal
    volumes:
    - data:/var/lib/registry
    - ./htpasswd:/auth/htpasswd
    - ./config.yaml:/etc/docker/registry/config.yml
networks:
  internal:
    external: true
    name: internal
volumes:
  data:
