version: "3.7"

services:
  landing-page:
    image: docker.yourdomain.com/landing-page:latest
    restart: always
    environment:
    - VIRTUAL_HOST=yourdomain.com
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=yourdomain.com
    - LETSENCRYPT_EMAIL=email@domain.com
    networks:
    - internal
    expose:
    - "80"
networks:
  internal:
    external: true
    name: internal
