version: "3.7"
services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
    - "443:443"
    - "80:80"
    environment:
    - ENABLE_IPV6=true
    - VIRTUAL_PROTO=https
    - VIRTUAL_PORT=443
    - DEFAULT_HOST=dabbertorres.dev
    networks:
    - internal
    - external
    volumes:
    - proxy-configs:/etc/nginx/conf.d
    - vhosts:/etc/nginx/vhost.d
    - http-challenges:/usr/share/nginx/html
    - certs:/etc/nginx/certs:ro
  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    command: ["-notify-sighup", "nginx", "-watch", "-only-published", "/etc/docker-gen/templates/nginx.tmpl", "/etc/nginx/conf.d/default.conf"]
    networks:
    - internal
    volumes:
    - proxy-configs:/etc/nginx/conf.d
    - vhosts:/etc/nginx/vhost.d
    - http-challenges:/usr/share/nginx/html
    - certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /root/reverse-proxy:/etc/docker-gen/templates
  proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
    - internal
    environment:
    - NGINX_DOCKER_GEN_CONTAINER=docker-gen
    - NGINX_PROXY_CONTAINER=nginx
    volumes:
    - proxy-configs:/etc/nginx/conf.d
    - vhosts:/etc/nginx/vhost.d
    - http-challenges:/usr/share/nginx/html
    - certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
  internal:
    external: true
    name: internal
  external:
    external: true
    name: external
volumes:
  proxy-configs:
  vhosts:
  http-challenges:
  certs:
