version: "3.7"

services:
  ci:
    image: drone/drone:1.0.0-rc.6
    container_name: ci
    environment:
    - VIRTUAL_HOST=ci.dabbertorres.dev
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=ci.dabbertorres.dev
    - LETSENCRYPT_EMAIL=<email>
    - DRONE_GITEA_SERVER=https://git.dabbertorres.dev
    - DRONE_GIT_ALWAYS_AUTH=false
    - DRONE_RUNNER_CAPACITY=4
    - DRONE_SERVER_HOST=ci.dabbertorres.dev
    - DRONE_SERVER_PROTO=http
    - DRONE_TLS_AUTOCERT=false
    - DRONE_OPEN=false
    ports:
    - 80
    - 443
    volumes:
    - data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - internal

networks:
  internal:
    external: true
    name: internal

volumes:
  data:
